name: Update Authorized Keys on Servers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  roadrunner:
    env:
      HOST: roadrunner.connecta-regensburg.de
      PORT: 22
      USER: conny

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add authorized_keys to {{ github.job }}
        run: |
          echo "{{ vars.KEY_PUB }}" >> ${{ github.job }}
          echo "{{ secrets.KEY_PRIVATE }}" > private_key
          chmod 600 private_key
          scp -P ${{ env.PORT }} -i private_key ${{ github.job }} ${{ env.USER }}@${{ env.HOST }}:.ssh/authorized_keys
          ssh -p ${{ env.PORT }} -i private_key ${{ env.USER }}@${{ env.HOST }} 'chmod 600 ~/.ssh/authorized_keys && sudo systemctl restart sshd'
        continue-on-error: true
      - name: Remove private_key
        run: rm private_key
