name: Update Authorized Keys on Servers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  roadrunner:
    env:
      HOST: roadrunner.connecta-regensburg.de
      PORT: 22
      USER: conny
      FILE: ${{ github.job }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: generate authorized_keys
        run: |
          echo "{{ vars.KEY_PUB }}" >> ${{ env.FILE }}
          echo "{{ secrets.KEY_PRIVATE }}" > private_key
          sudo chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan -t ssh-ed25519 -p ${{ env.PORT }} ${{ env.HOST }} >> ~/.ssh/known_hosts
      - name: Copy authorized_keys to server
        run: |
          scp -P ${{ env.PORT }} -i ./private_key ${{ env.FILE }} ${{ env.USER }}@${{ env.HOST }}:.ssh/authorized_keys
      - name: Restart sshd
        run: |
          ssh -p ${{ env.PORT }} -i ./private_key ${{ env.USER }}@${{ env.HOST }} 'chmod 600 ~/.ssh/authorized_keys && sudo systemctl restart sshd'

      - name: Remove private_key
        if: always()
        run: rm private_key
