name: Update all keys

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  eagle:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: eagle
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}

  bugsbunny:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: bugsbunny
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}

  roadrunner:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: roadrunner
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}

  speicherschnecke-connecta:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: speicherschnecke-connecta
      RESTART_SSH: false
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}
