name: Update Authorized Keys on Servers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  roadrunner:
    env:
      HOST: roadrunner.connecta-regensburg.de
      PORT: 22
      USER: conny

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add root key
        run: |
          echo "{{ vars.KEY_PUB }}" >> ${{ github.job }}
      - name: Upload to server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.USER }}
          privateKey: ${{ secrets.KEY_PRIVATE }}
          local: ${{ github.job }}
          remote: ~/authorized_keys
      - name: Change permissions and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.USER }}
          key: ${{ secrets.KEY_PRIVATE }}
          script: |
            chmod 600 ~/.ssh/authorized_keys
            sudo systemctl restart sshd
            cat ~/.ssh/authorized_keys
            ls ~
            ls ~/.ssh
