name: Update Authorized Keys on Servers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  roadrunner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add root key
        run: |
          echo "{{ vars.KEY_PUB }}" >> ${{ github.job }}
      - name: Upload to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ github.job }}
          remote: authorized_keys
          host: roadrunner.connecta-regensburg.de
          port: 22
          username: user
          privateKey: ${{ secrets.KEY_PRIVATE }}
