name: Update Authorized Keys on Servers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  roadrunner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add root key
        run: |
          echo "{{ vars.KEY_PUB }}" >> ${{ github.job }}
      - name: Upload to server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: roadrunner.connecta-regensburg.de
          port: 22
          username: conny
          local: ${{ github.job }}
          remote: authorized_keys
          privateKey: ${{ secrets.KEY_PRIVATE }}
      - name: Change permissions and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: roadrunner.connecta-regensburg.de
          port: 22
          username: conny
          key: ${{ secrets.KEY_PRIVATE }}
          script: |
            chmod 600 ~/.ssh/authorized_keys
            sudo systemctl restart sshd
            echo ~/.ssh/authorized_keys
