name: Update Authorized Keys on Servers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  roadrunner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add root key
        run: |
          echo "{{ vars.KEY_PUB }}" >> ${{ github.job }}
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: roadrunner.connecta-regensburg.de
          port: 22
          username: user
          key: ${{ secrets.KEY_PRIVATE }}
          source: "{{ github.job }}"
          target: ~/.ssh/authorized_keys
