name: Update all keys

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  eagle:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: eagle
      RESTART_SSHD: true
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}

  bugsbunny:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: bugsbunny
      RESTART_SSHD: true
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}

  roadrunner:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: roadrunner
      RESTART_SSHD: true
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}

  mayfly:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: mayfly
      RESTART_SSH: true
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}

  speicherschnecke-connecta:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: speicherschnecke-connecta
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}
